moonbitlang/moonbit-docs

README.md

Only the basic idea and some examples. Some detailed behaviors are not covered

add doc for operator overloading

---

README.md

1. Update struct name, capitalize the first letter
2. Update builtin type name, capitalize the first letter

Update struct name and builtin type

---

.gitignore
examples/avl_tree/README.md
examples/avl_tree/lib/avl.mbt
examples/avl_tree/lib/moon.pkg
examples/avl_tree/main/main.mbt
examples/avl_tree/main/moon.pkg
examples/avl_tree/moon.mod

Use Moonbit to implement an [AVL tree](https://en.wikipedia.org/wiki/AVL_tree), with printer to show its internal.

Add AVL tree demo

---

examples/multidimensional_arrays/README.md
examples/multidimensional_arrays/lib/arrays.mbt
examples/multidimensional_arrays/lib/moon.pkg
examples/multidimensional_arrays/main/main.mbt
examples/multidimensional_arrays/main/moon.pkg
examples/multidimensional_arrays/moon.mod

Use the [triangle problem](https://leetcode.com/problems/triangle/) to demonstrate how to use Moonbit's multidimensional arrays.

Add multidimensional arrays demo

---

examples/palindrome_string/README.md
examples/palindrome_string/lib/moon.pkg
examples/palindrome_string/lib/str_iter.mbt
examples/palindrome_string/main/main.mbt
examples/palindrome_string/main/moon.pkg
examples/palindrome_string/moon.mod

Use the palindrome question to demonstrate Moonbit's string iteration.

Add string iteration demo

---

README.md

Add number section in readme

---

moon_build_system_tutorial.md

tweak build system tutorial

---

examples/avl_tree/lib/avl.mbt
examples/avl_tree/main/main.mbt
examples/buffer/lib/buffer.mbt
examples/docstring-demo/lib/hello.mbt
examples/docstring-demo/main/main.mbt
examples/multidimensional_arrays/lib/arrays.mbt
examples/multidimensional_arrays/main/main.mbt
examples/number/main/main.mbt
examples/palindrome_string/lib/str_iter.mbt
examples/palindrome_string/main/main.mbt
examples/unicode_demo/main/main.mbt

Update examples for new print and println

Update examples for new print and println

---

zh-docs/README.md

update zh docs

---

README.md
zh-docs/README.md

Add continue and break examples

---

README.md

fix minor styles issue

---

README.md
zh-docs/README.md

should be available publicly on 2.5

add doc for [Trait::method] call syntax

---

README.md
zh-docs/README.md

#192 我修了这个问题，没问题的话帮 merge 到主干去

fix: wrong return type of Ref

---

examples/cf_worker/README.md

fix: A typo on cf worker doc

---

README.md
zh-docs/README.md

add docs for pragmas

---

README.md
zh-docs/README.md

fix view syntax

---

ffi-and-wasm-host.md
zh-docs/ffi-and-wasm-host.md

update default backend to WasmGC

---

README.md
zh-docs/README.md

update document with `impl Trait for Type with method_name(...) { ... }` syntax

update doc with `impl` syntax

---

tour.md
zh-docs/tour.md

I've replace every Debug with Show to align with the changes in core. A introduction of newtype is also added, aloneside some language refinements.

improvement for tour.md

---

README.md
zh-docs/README.md

The `Debug` trait is now merged into the `Show` trait

update doc for [Show] & cleanup doc for [Debug]

---

moonbit-docs/docs/README.md
moonbit-docs/i18n/zh/docusaurus-plugin-content-docs/current/README.md

simplify if-expr-true-else-false with expr

---

moonbit-docs/docs/README.md
moonbit-docs/i18n/zh/docusaurus-plugin-content-docs/current/README.md

the latest compiler release:
- add abstract and readonly visibility to traits
- will port the semantic of `pub trait` and `pub type` to readonly in the future: to declare fully public traits/types, use `pub(open)`/`pub(all)` instead
- currently `pub trait` and `pub type` is still fully public, for compatibility sake, but will trigger a compiler warning

update doc for visibility of types and traits

---

next/toolchain/moon/commands.md

Close https://github.com/moonbitlang/moonbit-docs/issues/356

docs(moon): update command line help

---

next/language/ffi-and-wasm-host.md

fix: FFI example

---

next/locales/zh_CN/LC_MESSAGES/example.po

Added the translation for Myers diff

Update Myers diff translation

---

next/language/fundamentals.md
next/sources/language/src/is/top.mbt

This should be merged with next release

doc: improve is expression

---

next/locales/zh_CN/LC_MESSAGES/language.po

Fixed the basic docs (language.po) of the moonbit. There are some places that not translated.

add translation in language.po

---

next/locales/zh_CN/LC_MESSAGES/example.po

Add Chinese translation for the introduction of G-machine; Myers diff1; Myers diff 2; Myers diff 3. 
And modify some errors:
There are two boundary cases: k == -d and k == d.
When k == -d, you can only choose v[k + 1].
When k == -d, you can only choose v[k - 1].

Add Chinese translation and modify errors for example.po

---

next/language/C-ffi.md
next/language/index.md
next/locales/zh_CN/LC_MESSAGES/language.po

add documentation for MoonBit's C FFI

add doc for C FFI

---

next/language/fundamentals.md
next/locales/zh_CN/LC_MESSAGES/language.po
next/sources/language/src/pattern/top.mbt

这里好像有些问题，能不能帮忙看下 @peter-jerry-ye

doc(array pattern)

---

moonbit-tour/build/page.ts
moonbit-tour/index.html

feat: auto select language version

---

next/locales/zh_CN/LC_MESSAGES/tutorial.po

Changed some English punctuation marks in the Chinese section to Chinese punctuation marks; improved some of the translations.

Chinese Punctuation Changing & Translation Improvement

---

next/language/ffi.md

the same issue also in https://docs.moonbitlang.com/en/latest/language/error_codes/E4151.html#e4151

replace `capture-free function` with `closed function` in ffi.md

---

next/language/ffi.md

for terminology  convention.
* free memory
* release resource
* destroy object

Modify the terminology in lifetime management

---

next/sources/language/src/pattern/top.mbt
next/sources/segment-tree/src/part1/top.mbt
next/sources/segment-tree/src/part2/top.mbt

Json::Number is invisible, use Json::number itead.
Json::Null is invisible, use Json::null instead

fix(next): Json constructor invisible, use smart constructor 

---

next/language/error_codes/E4150.md

https://www.moonbitlang.com/weekly-updates/2025/04/21/index#language-updates

Update Async function application syntax in  E4150.md

---

next/language/fundamentals.md
next/locales/zh_CN/LC_MESSAGES/language.po
next/sources/language/src/is/top.mbt

more on is-expression

---

next/language/packages.md
next/locales/zh_CN/LC_MESSAGES/language.po

https://github.com/moonbitlang/moonbit-docs/blob/main/next/language/methods.md?plain=1#L190-L192

docs: fix empty traits note

---

moonbit-tour/build/scan-tour.ts
moonbit-tour/index.html
moonbit-tour/src/toc.ts

主要包含2个样式上的改动
1. toc 打开时支持动画
2. 内部章节选中态样式增加
3. 
https://github.com/user-attachments/assets/bb4d3ee4-3926-4fc3-907e-57fdc17dfa14

完善tour中toc部分交互和样式

---

next/language/error_codes/E4016.md
next/locales/zh_CN/LC_MESSAGES/language.po

fix: mark E4016 as dead

---

next/locales/zh_CN/LC_MESSAGES/language.po

see https://github.com/moonbitlang/moonbit-docs/issues/453

fix: translation error in the language.po

---

next/locales/zh_CN/LC_MESSAGES/language.po

typo: legacy ! op

---

next/language/fundamentals.md
next/locales/zh_CN/LC_MESSAGES/language.po
next/sources/language/src/controls/top.mbt

add document for the newly introduced `defer` construct

add document for `defer`

---

moonbit-tour/tour/chapter1_basics/lesson15_module_and_package/index.mbt
moonbit-tour/tour/chapter1_basics/lesson15_module_and_package/index.md
moonbit-tour/tour/zh/chapter1_basics/lesson15_module_and_package/index.mbt
moonbit-tour/tour/zh/chapter1_basics/lesson15_module_and_package/index.md

Add a lesson to introduce the build system, package registry, module and package.

doc: add chapter 1, lesson 15
