moonbitlang/moonbit-docs

examples/buffer/lib/buffer.mbt
examples/path/lib/string.mbt
examples/string/lib/string.mbt

examples/buffer, examples/path, examples/string still build failed
output:
moonbit-docs/examples/buffer/main/main.mbt:16:7-16:12 Error (warning 015): The mutability of 'index' is never used
moonbit-docs/examples/path/lib/string.mbt:13:13-13:23 Error (warning 015): The mutability of 'new_result' is never used.
moonbit-docs/examples/path/lib/string.mbt:127:7-127:8 Error (warning 015): The mutability of 'n' is never used.
moonbit-docs/examples/path/lib/string.mbt:152:7-152:12 Error (warning 015): The mutability of 'array' is never used.
moonbit-docs/examples/string/lib/string.mbt:13:13-13:23 Error (warning 015): The mutability of 'new_result' is never used.
moonbit-docs/examples/string/lib/string.mbt:127:7-127:8 Error (warning 015): The mutability of 'n' is never used. …

fix: change array_make to Array::make

---

build-system-tutorial.md
zh-docs/build-system-tutorial.md

当前文档中对 `moon new` 命令的使用方式描述不正确（已不能使用 `hello` 作为参数），本 PR 修复文档中相关的表述

chore: fix moon new usage

---

zh-docs/README.md

函数类型定义
```
f: (S) -> T
```
误写成
```
f: (S) => T
```

修改zh-docs中的错误

---

README.md
zh-docs/README.md

The color of `array` make me feel it's a keyword.
Before:
After:

docs(Array): rename array to numbers

---

build-system-tutorial.md
zh-docs/build-system-tutorial.md

Hi all,
The funtion `assert_eq` in `build-system-tutorial.md` can't be compiled successfully because the return value of the top funtion requires explicit type annotation [1][2]. This patch fixes it.
Thanks for taking the time to review.
Best Regards,
-- Guoxiong
[1] https://www.moonbitlang.com/weekly-updates#3-now-a-top-level-function-without-a-marked-return-value-is-an-error
[2] https://www.moonbitlang.com/docs/syntax#top-level-functions

Add return type in assert_eq

---

README.md
zh-docs/README.md

Hi all,
When the return types are missed in the methods of the traits, they can't be compiled successfully now. So it is good to add them.
Thanks for taking the time to review.
Best Regards,
-- Guoxiong

Add return types in the methods of the traits

---

README.md
zh-docs/README.md

Hi all,
This patch removes a wrong comma in enum. The previous code snippet can't be compiled.
Thanks for taking the time to review.
Best Regards,
-- Guoxiong

Remove a wrong comma in enum

---

README.md
zh-docs/README.md

Hi all,
When I read `_[_](get item)` first time, I misunderstood it as one or two underline `_`. I searched `op_get` and `op_set` in the core library, then I knew what I misunderstood. So I think it is good to provide an example about `op_get` and `op_set`.
Thanks for your review.
Best Regards,
-- Guoxiong

Add an example about operator overloading

---

README.md

Just found a tiny mistake.
The code in the original document doesn't work for me.
It throws following error
```
$ moon run main
failed: moonc build-package /home/d2verb/workspace/misc/study/moonbit/sample/main/main.mbt -o /home/d2verb/workspace/misc/study/moonbit/sample/target/wasm/release/build/main/main.core -pkg d2verb/sample/main -is-main -std-path /home/d2verb/.moon/lib/core/target/bundle -i /home/d2verb/workspace/misc/study/moonbit/sample/target/wasm/release/build/lib/lib.mi:lib -pkg-sources d2verb/sample/main:/home/d2verb/workspace/misc/study/moonbit/sample/main
/home/d2verb/workspace/misc/study/moonbit/sample/main/main.mbt:3:3-3:10 Expr Type Mismatch
has type : Ref[Int]
wanted   : Int
```
The code I wrote
```rust
// main.mbt
fn incr(~counter : Ref[Int] = { val: 0 }) -> Int { …
```

fix: wrong return type

---

README.md
build-system-tutorial.md
zh-docs/README.md
zh-docs/build-system-tutorial.md

This PR addresses a minor typo - it changes `raidus` to `radius` in both English and Chinese.
I also think that the `live` code blocks are a stroke of genius, and noticed as I was reading through the documentation that there were many places where I wanted to click on "Run" but it was missing.
I realize that not _all_ code blocks in the documentation are meant to be run, so I tried to be careful to add only the ones that _looked_ like they should be able to run, although I could not figure out how to test these changes out locally.
Any recommendations on testing would be greatly appreciated.
Additionally, my copy of VSCode has a plugin called [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) which automatically formats tables to be more …

Fix minor typo and add more live codeblocks

---

.github/sync.yml
.github/workflows/sync-json-schema.yml
build-system-configuration.md
mod.schema.json
pkg.schema.json
zh-docs/build-system-configuration.md

The updated json schema and markdown docs themselves are included in this pr as well.
As I haven't find a good way to translate those markdown docs, chinese version is directly copied from the original.
JSON Schema auto update example:
https://github.com/notch1p/moonbit-docs/actions/runs/10347197977
https://github.com/notch1p/moonbit-docs/pull/2
markdown docs auto build example:
https://github.com/notch1p/moonbit-docs/pull/3
https://github.com/notch1p/moonbit-docs/actions/runs/10348725731

CI: Auto Sync json schema from moon & build markdown docs

---

moonbit-docs/docs/tour.md
moonbit-docs/i18n/zh/docusaurus-plugin-content-docs/current/tour.md

This PR has two contributions as follows:
- Update project structure description and command to run the project, which fixes the problem discussed in this comment: https://github.com/moonbitlang/moonbit-docs/issues/229#issuecomment-2282764418
- Format some code blocks to make it consistent with the output of `moon fmt` and still keeps information it tries to convey.
I believe that the tour is a crucial documentation that makes a first impression especially for newcomers and needs active maintenance. I understand that moonbit is still in its pre-beta stage, but as a moonbit beginner, I did fell really upset when the command described in tour fails to run. :face_holding_back_tears:

fix(tour): update project structure and format code blocks

---

moonbit-docs/docs/README.md
moonbit-docs/i18n/zh/docusaurus-plugin-content-docs/current/README.md

1. we now allow calling `impl` via dot syntax. The whole trait system doc is refactored to emphasize explicit `impl` more
2. add doc for range pattern

update doc: trait impl update & range pattern

---

moonbit-tour/src/main.ts
moonbit-tour/tour/chapter1_basics/lesson10_test/index.md
moonbit-tour/tour/chapter1_basics/lesson1_variable/index.md
moonbit-tour/tour/chapter1_basics/lesson2_numbers/index.md
moonbit-tour/tour/chapter1_basics/lesson4_array/index.md
moonbit-tour/tour/chapter1_basics/lesson5_string/index.md
moonbit-tour/tour/chapter1_basics/lesson6_tuple/index.md
moonbit-tour/tour/chapter1_basics/lesson7_map/index.md
moonbit-tour/tour/chapter1_basics/lesson8_control_flow/index.md
moonbit-tour/tour/chapter1_basics/lesson9_for_in_loop/index.md
moonbit-tour/tour/chapter2_data_types/lesson1_struct/index.md
moonbit-tour/tour/chapter2_data_types/lesson2_mutable_field/index.md
moonbit-tour/tour/chapter2_data_types/lesson3_enum/index.md
moonbit-tour/tour/chapter2_data_types/lesson4_option/index.md
moonbit-tour/tour/chapter2_data_types/lesson5_result/index.md
moonbit-tour/tour/chapter3_pattern_matching/lesson1_introduction/index.md
moonbit-tour/tour/chapter3_pattern_matching/lesson2_let_and_match/index.md
moonbit-tour/tour/chapter3_pattern_matching/lesson3_constant_pattern/index.md
moonbit-tour/tour/chapter3_pattern_matching/lesson4_tuple_pattern/index.md
moonbit-tour/tour/chapter3_pattern_matching/lesson6_array_pattern/index.md
moonbit-tour/tour/chapter3_pattern_matching/lesson7_or_pattern/index.md

Feel free to close this PR if you do not agree with the proposed changes or only take bits and pieces of it.
I read through the full tour - great work... thank you for doing this!
I attempted to make some minor suggestions on improving the readability of the tour in the hopes that it will help others understand the content more easily.

Minor readability suggestions for the online MoonBit tour

---

next/language/fundamentals.md
next/sources/language/src/controls/top.mbt

#382 
Need next release to eliminate the warnings.

add doc for loop label

---

next/tutorial/tour.md

For proof reading: <https://moonbit-docs--413.org.readthedocs.build/en/413/>

doc: rewrite quick tour

---

document.code-workspace
next/README.md
next/conf.py

Translate author & modify environment for easier use.

doc(i18n): translate some extra stuff

---

.readthedocs.yaml
next/.gitignore
next/conf.py
next/example/index.md
next/language/index.md
next/llm.py
next/locales/zh_CN/LC_MESSAGES/example.po
next/locales/zh_CN/LC_MESSAGES/language.po
next/locales/zh_CN/LC_MESSAGES/toolchain.po
next/locales/zh_CN/LC_MESSAGES/tutorial.po
next/toolchain/index.md
next/tutorial/index.md

Add summary for each section. User may choose to download them for prompting LLMs.

feat: add summary for easier usage

---

next/toolchain/moon/package.md

`test-import` is already defined above, I think intention was to mention `test-import-all` option.

fix: test-import-all doc

---

next/sources/language/src/trait/top.mbt

Making the example trait be `pub(open)` and impl be `pub` would be more newbie-friendly, and then describing access control in detail elsewhere would be better.
It would be better to add more details about trait and impl here.
https://docs.moonbitlang.com/en/latest/language/packages.html#access-control
- #432

docs: Change trait to open and impl to pub.

---

.autocorrectrc
.github/workflows/typo.yml

This PR is to integrate [AutoCorrect](https://github.com/huacnlee/autocorrect) with the CI.
> AutoCorrect is a powerful tool to help you to improve copywriting, correct spaces, words, and punctuations between CJK. 
The AutoCorrect now checks out hundreds of issues, see [the CI run result](https://github.com/liuly0322/moonbit-docs/actions/runs/13610011704/job/38045911699).
I can make a separate PR to confirm and fix these typos, maybe after https://github.com/moonbitlang/moonbit-docs/pull/543 is merged.

chore: add autocorrect to CI

---

next/language/methods.md
next/locales/zh_CN/LC_MESSAGES/language.po
next/sources/language/src/builtin/top.mbt
next/sources/language/src/operator/top.mbt

We are migrating from method based operator overloading to trait based operator overloading. This PR update the operator overloading section of language doc.

update operator overloading doc

---

next/toolchain/moon/commands.md
next/toolchain/moon/package.md

This text describes the latest backend link options and includes a brief description of the fast-debugging-test feature.

Update the docs about stub-cc* flags and `tcc -run`

---

next/example/gmachine/gmachine-2.md
next/example/gmachine/gmachine-3.md

replace coref with coreF
- #607

docs: fix typo in G-Machine

---

next/language/ffi.md
next/locales/zh_CN/LC_MESSAGES/language.po

since this feature is only useful for FFI, I placed it in the FFI page. May move to language fundamental page if we allow native conversion to `Int` inside MoonBit in the future.

add doc for customize integer value of constant enum

---

next/language/fundamentals.md
next/locales/zh_CN/LC_MESSAGES/language.po

docs:  replace `foreign functions` with `functions from other packages`

---

.gitignore
next/language/error_codes/E0007.md
next/language/error_codes/E3007.md
next/language/error_codes/E3009.md
next/language/error_codes/E3012.md
next/language/error_codes/E4026.md
next/language/error_codes/E4028.md
next/language/error_codes/E4030.md
next/language/error_codes/E4033.md
next/language/error_codes/E4034.md
next/language/error_codes/E4043.md
next/language/error_codes/E4044.md
next/language/error_codes/E4045.md
next/language/error_codes/E4088.md
next/language/error_codes/E4092.md
next/language/error_codes/E4093.md
next/language/error_codes/E4136.md
next/locales/zh_CN/LC_MESSAGES/language.po
next/locales/zh_CN/LC_MESSAGES/tutorial.po
next/tutorial/tour.md

This PR is to practise the idea in [this issue](https://github.com/moonbitlang/moonbit-docs/issues/748).

docs: replace all `record' appearances referring to types with `struct'

---

next/language/fundamentals.md

The word "is" can easily be confused with "ls" if its first letter is capitalized

---

next/language/fundamentals.md
next/language/methods.md
next/language/packages.md
next/locales/zh_CN/LC_MESSAGES/language.po
next/sources/language/src/method/top.mbt

- update doc for method, add local method
- update doc for trait implementation: case where every method has default implementation
- update syntax for `typealias`

adapt syntax & semantic change

---

next/language/ffi.md

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array

Fix typo: change 'UInt8Array' to 'Uint8Array'
